version: '3.1'


volumes:
  db-volume:
  conf:
  vhost:
  html:
  certs:

services:

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    network_mode: bridge

  docker-gen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    network_mode: bridge

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment: 
      - NGINX_DOCKER_GEN_CONTAINER=${NGINX_DOCKER_GEN_CONTAINER}
    network_mode: bridge

  db:
    image: mysql
    container_name: mysql-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    depends_on: 
      - nginx-proxy
      - letsencrypt
      - docker-gen
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - db-volume:/var/lib/mysql
    network_mode: bridge

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment: 
      - VIRTUAL_HOST=${APP_VIRTUAL_HOST}
      - VIRTUAL_POST=${APP_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${APP_VIRTUAL_HOST}
    depends_on: 
      - db
      - nginx-proxy
      - letsencrypt
      - docker-gen
    network_mode: bridge



